import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'ru' | 'kk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'nav.home': 'Home',
    'nav.planner': 'Trip Planner',
    'nav.translator': 'Translator',
    'nav.maps': 'Maps',
    'nav.mytrips': 'My Trips',
    'nav.signin': 'Sign In',
    'nav.contact': 'Contact Us',
    'nav.logout': 'Logout',

    // Hero
    'hero.title': 'Plan Your Dream Trip',
    'hero.subtitle': 'Smart travel planning within your budget',
    'hero.description': 'Create perfect itineraries, translate phrases, and explore destinations - all in one place',
    'hero.cta': 'Get Started',

    // Features
    'features.title': 'Everything You Need for Travel',
    'features.subtitle': 'Comprehensive tools for planning and enjoying your trips',
    'features.planner.title': 'Trip Planner',
    'features.planner.description': 'Plan trips with automatic budget calculation and expense tracking',
    'features.translator.title': 'Translator',
    'features.translator.description': 'Translate phrases and communicate easily in any language',
    'features.maps.title': 'Interactive Maps',
    'features.maps.description': 'Find attractions, hotels, and restaurants on interactive maps',

    // Trip Planner
    'planner.title': 'Trip Planner',
    'planner.subtitle': 'Create your perfect trip within your budget',
    'planner.tripDetails': 'Trip Details',
    'planner.totalBudgetLabel': 'Total Budget ($)',
    'planner.durationLabel': 'Duration (days)',
    'planner.travelersLabel': 'Number of Travelers',
    'planner.budgetPerDay': 'Budget per day:',
    'planner.perPersonPerDay': 'Per person per day:',
    'planner.recommendedDest': 'Recommended Destinations',
    'planner.basedOnBudget': 'Based on your budget of',
    'planner.perPersonPerDayShort': 'per person per day',
    'planner.noBudget': 'No destinations found within your budget. Try increasing your budget or reducing the number of days.',
    'planner.detailedBreakdown': 'Detailed Breakdown for',
    'planner.totalTripCost': 'Total Trip Cost:',
    'planner.destination': 'Destination',
    'planner.destination.placeholder': 'e.g., Paris, France',
    'planner.dates': 'Travel Dates',
    'planner.startDate': 'Start Date',
    'planner.endDate': 'End Date',
    'planner.budget': 'Budget per Day ($)',
    'planner.days': 'days',
    'planner.expenses': 'Planned Expenses',
    'planner.expense.category': 'Category',
    'planner.expense.amount': 'Amount ($)',
    'planner.expense.description': 'Description',
    'planner.addExpense': 'Add Expense',
    'planner.removeExpense': 'Remove',
    'planner.summary': 'Trip Summary',
    'planner.totalBudget': 'Total Budget',
    'planner.totalExpenses': 'Total Expenses',
    'planner.remaining': 'Remaining',
    'planner.exceeded': 'Over Budget',
    'planner.saveTrip': 'Save Trip',
    'planner.loginToSave': 'Sign in to save your trips',
    'planner.categories.accommodation': 'Accommodation',
    'planner.categories.food': 'Food',
    'planner.categories.transport': 'Transport',
    'planner.categories.activities': 'Activities',
    'planner.categories.shopping': 'Shopping',
    'planner.categories.other': 'Other',
    'planner.tripSavedSuccess': 'Trip saved successfully!',
    'planner.signInToSave': 'Please sign in to save your trip plan',
    'planner.selectDestFirst': 'Please select a destination first',
    // Budget Planner Card
    'planner.actualCost': 'Actual Trip Cost',
    'planner.budgetBreakdown': 'Budget Breakdown',
    'planner.insufficientBudget': 'Your budget is not enough for this trip. Choose fewer days or increase your budget.',
    'planner.freeBalance': 'Free Funds / Remaining Budget',
    'planner.hotel': 'Hotel',
    'planner.food': 'Food',
    'planner.leisure': 'Leisure',
    'planner.transport': 'Transport',
    'planner.saveBtn': 'Save Trip',
    'planner.savedSuccess': 'saved successfully!',
    'planner.noResults': 'No destinations found within your budget. Try increasing your budget or reducing the number of days.',
    'planner.hint': 'We show destinations where the daily rate per person fits your budget (up to 30% over).',
    'planner.dailyPerPerson': 'Daily per person',
    'common.day': 'day',
    'common.days': 'days',
    'common.people': 'people',
    'common.saving': 'Saving...',

    // Translator
    'translator.title': 'Translator',
    'translator.subtitle': 'Translate phrases and communicate with locals without language barriers',
    'translator.from': 'From Language',
    'translator.to': 'To Language',
    'translator.enterText': 'Enter Text',
    'translator.translation': 'Translation',
    'translator.translate': 'Translate',
    'translator.translating': 'Translating...',
    'translator.phrases': 'Common Travel Phrases',
    'translator.phrasesSubtitle': 'Click on a phrase to translate it instantly',
    'translator.ctrlEnter': 'Press Ctrl+Enter to translate',
    'translator.swap': 'Swap languages',
    'translator.copy': 'Copy',
    'translator.copied': 'Copied!',
    'translator.supports': 'Supports 15+ languages',

    // Maps
    'maps.title': 'Interactive Map',
    'maps.subtitle': 'Explore attractions, hotels, and restaurants',
    'maps.search': 'Search places...',
    'maps.placeType': 'Place Type',
    'maps.all': 'All',
    'maps.attractions': 'Attractions',
    'maps.hotels': 'Hotels',
    'maps.restaurants': 'Restaurants',
    'maps.transport': 'Transport',
    'maps.coordinates': 'Coordinates',
    'maps.directions': 'Get Directions',
    'maps.placesFound': 'Places Found',
    'maps.noPlaces': 'No places found',
    'maps.tryAgain': 'Try changing your search query',

    // My Trips
    'mytrips.title': 'My Trips',
    'mytrips.subtitle': 'Your saved travel plans',
    'mytrips.noTrips': 'No Saved Trips Yet',
    'mytrips.startPlanning': 'Start planning your next adventure and save your trips here',
    'mytrips.goToPlanner': 'Go to Trip Planner',
    'mytrips.delete': 'Delete',
    'mytrips.removeTrip': 'Remove Trip',
    'mytrips.budget': 'Budget',
    'mytrips.expenses': 'Expenses',
    'mytrips.signInRequired': 'Sign In Required',
    'mytrips.signInMessage': 'Please sign in to view your saved trips',
    'mytrips.days': 'days',
    'mytrips.traveler': 'traveler',
    'mytrips.travelers': 'travelers',
    'mytrips.savedOn': 'Saved on',
    'mytrips.removed': 'Trip removed successfully',

    // Footer
    'footer.company': 'Company',
    'footer.about': 'About Us',
    'footer.careers': 'Careers',
    'footer.blog': 'Blog',
    'footer.press': 'Press',
    'footer.support': 'Support',
    'footer.help': 'Help',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.terms': 'Terms',
    'footer.social': 'Social Media',
    'footer.rights': 'All rights reserved',
    'footer.admin': 'Admin: View Feedbacks',

    // Auth
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Full Name',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signinButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    'auth.welcomeBack': 'Welcome Back',
    'auth.signInAccess': 'Sign in to access your travel plans',
    'auth.startPlanning': 'Start planning your next adventure',
    'auth.createAccount': 'Create Account',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.enterName': 'Please enter your name',
    'auth.welcomeMsg': 'Welcome back! You are now signed in.',
    'auth.accountCreated': 'Your account has been created.',

    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': "Have questions or feedback? We'd love to hear from you!",
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': "What's this about?",
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us more...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.messageSent': 'Message Sent!',
    'contact.thankYou': "Thank you for your feedback. We'll get back to you soon.",
    'contact.reachUs': 'You can also reach us at',

    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
  },
  ru: {
    // Header
    'nav.home': 'Главная',
    'nav.planner': 'Планировщик',
    'nav.translator': 'Переводчик',
    'nav.maps': 'Карты',
    'nav.mytrips': 'Мои Поездки',
    'nav.signin': 'Войти',
    'nav.contact': 'Связаться',
    'nav.logout': 'Выйти',

    // Hero
    'hero.title': 'Планируйте Путешествие Мечты',
    'hero.subtitle': 'Умное планирование путешествий в рамках вашего бюджета',
    'hero.description': 'Создавайте идеальные маршруты, переводите фразы и исследуйте направления - все в одном месте',
    'hero.cta': 'Начать',

    // Features
    'features.title': 'Все Необходимое для Путешествий',
    'features.subtitle': 'Комплексные инструменты для планирования и наслаждения вашими поездками',
    'features.planner.title': 'Планировщик Поездок',
    'features.planner.description': 'Планируйте поездки с автоматическим расчетом бюджета и отслеживанием расходов',
    'features.translator.title': 'Переводчик',
    'features.translator.description': 'Переводите фразы и общайтесь легко на любом языке',
    'features.maps.title': 'Интерактивные Карты',
    'features.maps.description': 'Находите достопримечательности, отели и рестораны на интерактивных картах',

    // Trip Planner
    'planner.title': 'Планировщик Поездок',
    'planner.subtitle': 'Создайте идеальную поездку в рамках вашего бюджета',
    'planner.tripDetails': 'Детали Поездки',
    'planner.totalBudgetLabel': 'Общий Бюджет ($)',
    'planner.durationLabel': 'Продолжительность (дней)',
    'planner.travelersLabel': 'Количество Путешественников',
    'planner.budgetPerDay': 'Бюджет в день:',
    'planner.perPersonPerDay': 'На человека в день:',
    'planner.recommendedDest': 'Рекомендуемые Направления',
    'planner.basedOnBudget': 'На основе ��ашего бюджета',
    'planner.perPersonPerDayShort': 'на человека в день',
    'planner.noBudget': 'Направлений в рамках вашего бюджета не найдено. Попробуйте увеличить бюджет или сократить количество дней.',
    'planner.detailedBreakdown': 'Детальный Расчёт для',
    'planner.totalTripCost': 'Итоговая Стоимость:',
    'planner.destination': 'Направление',
    'planner.destination.placeholder': 'например, Париж, Франция',
    'planner.dates': 'Даты Поездки',
    'planner.startDate': 'Дата Начала',
    'planner.endDate': 'Дата Окончания',
    'planner.budget': 'Бюджет в День ($)',
    'planner.days': 'дней',
    'planner.expenses': 'Планируемые Расходы',
    'planner.expense.category': 'Категория',
    'planner.expense.amount': 'Сумма ($)',
    'planner.expense.description': 'Описание',
    'planner.addExpense': 'Добавить Расход',
    'planner.removeExpense': 'Удалить',
    'planner.summary': 'Итоги Поездки',
    'planner.totalBudget': 'Общий Бюджет',
    'planner.totalExpenses': 'Общие Расходы',
    'planner.remaining': 'Осталось',
    'planner.exceeded': 'Превышение Бюджета',
    'planner.saveTrip': 'Сохранить Поездку',
    'planner.loginToSave': 'Войдите, чтобы сохранить поездки',
    'planner.categories.accommodation': 'Проживание',
    'planner.categories.food': 'Питание',
    'planner.categories.transport': 'Транспорт',
    'planner.categories.activities': 'Развлечения',
    'planner.categories.shopping': 'Покупки',
    'planner.categories.other': 'Другое',
    'planner.tripSavedSuccess': 'Поездка сохранена!',
    'planner.signInToSave': 'Войдите, чтобы сохранить план поездки',
    'planner.selectDestFirst': 'Сначала выберите направление',
    // Budget Planner Card
    'planner.actualCost': 'Реальная стоимость поездки',
    'planner.budgetBreakdown': 'Распределение бюджета',
    'planner.insufficientBudget': 'Вашего бюджета недостаточно для этой поездки. Выберите меньше дней или увеличьте бюджет.',
    'planner.freeBalance': 'Свободные средства / Остаток бюджета',
    'planner.hotel': 'Отель',
    'planner.food': 'Еда',
    'planner.leisure': 'Досуг',
    'planner.transport': 'Транспорт',
    'planner.saveBtn': 'Сохранить поездку',
    'planner.savedSuccess': 'успешно сохранена!',
    'planner.noResults': 'Направлений в рамках вашего бюджета не найдено. Попробуйте увеличить бюджет или сократить количество дней.',
    'planner.hint': 'Мы показываем направления, где дневная стоимость на человека соответствует вашему бюджету (допуск до 30%).',
    'planner.dailyPerPerson': 'На человека в день',
    'common.day': 'день',
    'common.days': 'дней',
    'common.people': 'человек',
    'common.saving': 'Сохранение...',

    // Translator
    'translator.title': 'Переводчик',
    'translator.subtitle': 'Переводите фразы и общайтесь с местными жителями без языковых барьеров',
    'translator.from': 'С Языка',
    'translator.to': 'На Язык',
    'translator.enterText': 'Введите Текст',
    'translator.translation': 'Перевод',
    'translator.translate': 'Перевести',
    'translator.translating': 'Переводится...',
    'translator.phrases': 'Популярные Туристические Фразы',
    'translator.phrasesSubtitle': 'Нажмите на фразу, чтобы перевести её мгновенно',
    'translator.ctrlEnter': 'Нажмите Ctrl+Enter для перевода',
    'translator.swap': 'Поменять языки',
    'translator.copy': 'Копировать',
    'translator.copied': 'Скопировано!',
    'translator.supports': 'Поддерживает 15+ языков',

    // Maps
    'maps.title': 'Интерактивная Карта',
    'maps.subtitle': 'Исследуйте достопримечательности, отели и рестораны',
    'maps.search': 'Поиск мест...',
    'maps.placeType': 'Тип Места',
    'maps.all': 'Все',
    'maps.attractions': 'Достопримечательности',
    'maps.hotels': 'Отели',
    'maps.restaurants': 'Рестораны',
    'maps.transport': 'Транспорт',
    'maps.coordinates': 'Координаты',
    'maps.directions': 'Построить Маршрут',
    'maps.placesFound': 'Найдено Мест',
    'maps.noPlaces': 'Места не найдены',
    'maps.tryAgain': 'Попробуйте изменить поисковый запрос',

    // My Trips
    'mytrips.title': 'Мои Поездки',
    'mytrips.subtitle': 'Ваши сохранённые планы путешествий',
    'mytrips.noTrips': 'Нет Сохранённых Поездок',
    'mytrips.startPlanning': 'Начните планировать следующее путешествие и сохраняйте поездки здесь',
    'mytrips.goToPlanner': 'Перейти к Планировщику',
    'mytrips.delete': 'Удалить',
    'mytrips.removeTrip': 'Удалить Поездку',
    'mytrips.budget': 'Бюджет',
    'mytrips.expenses': 'Расходы',
    'mytrips.signInRequired': 'Требуется Вход',
    'mytrips.signInMessage': 'Пожалуйста, войдите, чтобы просмотреть сохранённые поездки',
    'mytrips.days': 'дней',
    'mytrips.traveler': 'путешественник',
    'mytrips.travelers': 'путешественников',
    'mytrips.savedOn': 'Сохранено',
    'mytrips.removed': 'Поездка удалена',

    // Footer
    'footer.company': 'Компания',
    'footer.about': 'О нас',
    'footer.careers': 'Карьера',
    'footer.blog': 'Блог',
    'footer.press': 'Пресса',
    'footer.support': 'Поддержка',
    'footer.help': 'Помощь',
    'footer.contact': 'Контакты',
    'footer.faq': 'FAQ',
    'footer.terms': 'Условия',
    'footer.social': 'Социальные Сети',
    'footer.rights': 'Все права защищены',
    'footer.admin': 'Админ: Просмотр Отзывов',

    // Auth
    'auth.signin': 'Войти',
    'auth.signup': 'Регистрация',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.name': 'Полное Имя',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.signinButton': 'Войти',
    'auth.signupButton': 'Создать Аккаунт',
    'auth.welcomeBack': 'С Возвращением',
    'auth.signInAccess': 'Войдите, чтобы получить доступ к вашим поездкам',
    'auth.startPlanning': 'Начните планировать следующее приключение',
    'auth.createAccount': 'Создать Аккаунт',
    'auth.signingIn': 'Вход...',
    'auth.creatingAccount': 'Создание аккаунта...',
    'auth.enterName': 'Пожалуйста, введите ваше имя',
    'auth.welcomeMsg': 'С возвращением! Вы вошли в систему.',
    'auth.accountCreated': 'Ваш аккаунт создан.',

    // Contact
    'contact.title': 'Свяжитесь с Нами',
    'contact.subtitle': 'Есть вопросы или пожелания? Мы рады услышать вас!',
    'contact.name': 'Имя',
    'contact.email': 'Email',
    'contact.subject': 'Тема',
    'contact.subjectPlaceholder': 'О чём вы хотите написать?',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите подробнее...',
    'contact.send': 'Отправить',
    'contact.sending': 'Отправка...',
    'contact.messageSent': 'Сообщение отправлено!',
    'contact.thankYou': 'Спасибо за ваш отзыв. Мы свяжемся с вами в ближайшее время.',
    'contact.reachUs': 'Вы также можете написать нам на',

    // Common
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.close': 'Закрыть',
  },
  kk: {
    // Header
    'nav.home': 'Басты бет',
    'nav.planner': 'Жоспарлаушы',
    'nav.translator': 'Аудармашы',
    'nav.maps': 'Карталар',
    'nav.mytrips': 'Менің сапарларым',
    'nav.signin': 'Кіру',
    'nav.contact': 'Байланыс',
    'nav.logout': 'Шығу',

    // Hero
    'hero.title': 'Арман сапарыңызды жоспарлаңыз',
    'hero.subtitle': 'Бюджетіңізге сай ақылды саяхат жоспарлау',
    'hero.description': 'Мінсіз маршруттар жасаңыз, сөз тіркестерін аударыңыз және бағыттарды зерттеңіз - барлығы бір жерде',
    'hero.cta': 'Бастау',

    // Features
    'features.title': 'Саяхат үшін қажеттінің бәрі',
    'features.subtitle': 'Сапарларыңызды жоспарлауға және ләззат алуға арналған кешенді құралдар',
    'features.planner.title': 'Сапар жоспарлаушы',
    'features.planner.description': 'Автоматты бюджет есебі және шығыстарды бақылау арқылы сапарларды жоспарлаңыз',
    'features.translator.title': 'Аудармашы',
    'features.translator.description': 'Сөз тіркестерін аударыңыз және кез келген тілде оңай сөйлесіңіз',
    'features.maps.title': 'Интерактивті карталар',
    'features.maps.description': 'Интерактивті карталарда көрікті жерлерді, қонақүйлер мен мейрамханаларды табыңыз',

    // Trip Planner
    'planner.title': 'Сапар жоспарлаушы',
    'planner.subtitle': 'Бюджетіңізге сай мінсіз сапар жасаңыз',
    'planner.tripDetails': 'Сапар мәліметтері',
    'planner.totalBudgetLabel': 'Жалпы бюджет ($)',
    'planner.durationLabel': 'Ұзақтығы (күн)',
    'planner.travelersLabel': 'Саяхатшылар саны',
    'planner.budgetPerDay': 'Күндік бюджет:',
    'planner.perPersonPerDay': 'Адам басына күніне:',
    'planner.recommendedDest': 'Ұсынылатын бағыттар',
    'planner.basedOnBudget': 'Сіздің бюджетіңіз негізінде',
    'planner.perPersonPerDayShort': 'адам басына күніне',
    'planner.noBudget': 'Бюджетіңізге сәйкес бағыттар табылмады. Бюджетті арттырып немесе күндер санын азайтып көріңіз.',
    'planner.detailedBreakdown': 'Толық есеп:',
    'planner.totalTripCost': 'Жалпы сапар құны:',
    'planner.destination': 'Бағыт',
    'planner.destination.placeholder': 'мысалы, Париж, Франция',
    'planner.dates': 'Сапар күндері',
    'planner.startDate': 'Басталу күні',
    'planner.endDate': 'Аяқталу күні',
    'planner.budget': 'Күндік бюджет ($)',
    'planner.days': 'күн',
    'planner.expenses': 'Жоспарланған шығыстар',
    'planner.expense.category': 'Санат',
    'planner.expense.amount': 'Сома ($)',
    'planner.expense.description': 'Сипаттама',
    'planner.addExpense': 'Шығыс қосу',
    'planner.removeExpense': 'Жою',
    'planner.summary': 'Сапар қорытындысы',
    'planner.totalBudget': 'Жалпы бюджет',
    'planner.totalExpenses': 'Жалпы шығыстар',
    'planner.remaining': 'Қалдық',
    'planner.exceeded': 'Бюджет асып кетті',
    'planner.saveTrip': 'Сапарды сақтау',
    'planner.loginToSave': 'Сапарларды сақтау үшін кіріңіз',
    'planner.categories.accommodation': 'Тұрғын үй',
    'planner.categories.food': 'Тамақ',
    'planner.categories.transport': 'Көлік',
    'planner.categories.activities': 'Ойын-сауық',
    'planner.categories.shopping': 'Сауда',
    'planner.categories.other': 'Басқа',
    'planner.tripSavedSuccess': 'Сапар сәтті сақталды!',
    'planner.signInToSave': 'Сапар жоспарын сақтау үшін кіріңіз',
    'planner.selectDestFirst': 'Алдымен бағыт таңдаңыз',
    // Budget Planner Card
    'planner.actualCost': 'Сапардың нақты құны',
    'planner.budgetBreakdown': 'Бюджетті бөлу',
    'planner.insufficientBudget': 'Бюджетіңіз бұл сапарға жетпейді. Күндер санын азайтыңыз немесе бюджетті арттырыңыз.',
    'planner.freeBalance': 'Бос қаражат / Бюджет қалдығы',
    'planner.hotel': 'Қонақүй',
    'planner.food': 'Тамақ',
    'planner.leisure': 'Демалыс',
    'planner.transport': 'Көлік',
    'planner.saveBtn': 'Сапарды сақтау',
    'planner.savedSuccess': 'сәтті сақталды!',
    'planner.noResults': 'Бюджетіңізге сәйкес бағыттар табылмады. Бюджетті арттырып немесе күндер санын азайтып көріңіз.',
    'planner.hint': 'Адам басына күндік тариф бюджетіңізге сәйкес келетін бағыттарды (30% артыққа дейін) көрсетеміз.',
    'planner.dailyPerPerson': 'Адам басына күніне',
    'common.day': 'күн',
    'common.days': 'күн',
    'common.people': 'адам',
    'common.saving': 'Сақталуда...',

    // Translator
    'translator.title': 'Аудармашы',
    'translator.subtitle': 'Сөз тіркестерін аударыңыз және тіл кедергісінсіз жергілікті тұрғындармен сөйлесіңіз',
    'translator.from': 'Қай тілден',
    'translator.to': 'Қай тілге',
    'translator.enterText': 'Мәтін енгізіңіз',
    'translator.translation': 'Аударма',
    'translator.translate': 'Аудару',
    'translator.translating': 'Аударылуда...',
    'translator.phrases': 'Жиі қолданылатын туристік сөз тіркестері',
    'translator.phrasesSubtitle': 'Лезде аудару үшін сөз тіркесін басыңыз',
    'translator.ctrlEnter': 'Аудару үшін Ctrl+Enter басыңыз',
    'translator.swap': 'Тілдерді ауыстыру',
    'translator.copy': 'Көшіру',
    'translator.copied': 'Көшірілді!',
    'translator.supports': '15+ тілді қолдайды',

    // Maps
    'maps.title': 'Интерактивті карта',
    'maps.subtitle': 'Көрікті жерлерді, қонақүйлер мен мейрамханаларды зерттеңіз',
    'maps.search': 'Орындарды іздеу...',
    'maps.placeType': 'Орын түрі',
    'maps.all': 'Барлығы',
    'maps.attractions': 'Көрікті жерлер',
    'maps.hotels': 'Қонақүйлер',
    'maps.restaurants': 'Мейрамханалар',
    'maps.transport': 'Көлік',
    'maps.coordinates': 'Координаттар',
    'maps.directions': 'Бағыт алу',
    'maps.placesFound': 'Орындар табылды',
    'maps.noPlaces': 'Орындар табылмады',
    'maps.tryAgain': 'Іздеу сұрауыңызды өзгертіп көріңіз',

    // My Trips
    'mytrips.title': 'Менің сапарларым',
    'mytrips.subtitle': 'Сіздің сақталған саяхат жоспарларыңыз',
    'mytrips.noTrips': 'Сақталған сапарлар жоқ',
    'mytrips.startPlanning': 'Келесі саяхатыңызды жоспарлай бастаңыз және сапарларыңызды осында сақтаңыз',
    'mytrips.goToPlanner': 'Жоспарлаушыға өту',
    'mytrips.delete': 'Жою',
    'mytrips.removeTrip': 'Сапарды жою',
    'mytrips.budget': 'Бюджет',
    'mytrips.expenses': 'Шығыстар',
    'mytrips.signInRequired': 'Кіру қажет',
    'mytrips.signInMessage': 'Сақталған сапарларды көру үшін кіріңіз',
    'mytrips.days': 'күн',
    'mytrips.traveler': 'саяхатшы',
    'mytrips.travelers': 'саяхатшы',
    'mytrips.savedOn': 'Сақталды',
    'mytrips.removed': 'Сапар жойылды',

    // Footer
    'footer.company': 'Компания',
    'footer.about': 'Біз туралы',
    'footer.careers': 'Мансап',
    'footer.blog': 'Блог',
    'footer.press': 'Баспасөз',
    'footer.support': 'Қолдау',
    'footer.help': 'Көмек',
    'footer.contact': 'Байланыс',
    'footer.faq': 'Жиі қойылатын сұрақтар',
    'footer.terms': 'Шарттар',
    'footer.social': 'Әлеуметтік желілер',
    'footer.rights': 'Барлық құқықтар қорғалған',
    'footer.admin': 'Әкімші: Пікірлерді қарау',

    // Auth
    'auth.signin': 'Кіру',
    'auth.signup': 'Тіркелу',
    'auth.email': 'Email',
    'auth.password': 'Құпия сөз',
    'auth.name': 'Толық аты',
    'auth.noAccount': 'Тіркелгіңіз жоқ па?',
    'auth.haveAccount': 'Тіркелгіңіз бар ма?',
    'auth.signinButton': 'Кіру',
    'auth.signupButton': 'Тіркелгі жасау',
    'auth.welcomeBack': 'Қайта келдіңіз',
    'auth.signInAccess': 'Сапарларыңызға кіру үшін жүйеге кіріңіз',
    'auth.startPlanning': 'Келесі шытырман оқиғаны жоспарлай бастаңыз',
    'auth.createAccount': 'Тіркелгі жасау',
    'auth.signingIn': 'Кіру...',
    'auth.creatingAccount': 'Тіркелгі жасалуда...',
    'auth.enterName': 'Атыңызды енгізіңіз',
    'auth.welcomeMsg': 'Қайта келдіңіз! Жүйеге кірдіңіз.',
    'auth.accountCreated': 'Тіркелгіңіз жасалды.',

    // Contact
    'contact.title': 'Бізбен байланысыңыз',
    'contact.subtitle': 'Сұрақтарыңыз немесе ұсыныстарыңыз бар ма? Сізден хабар алғанымызға қуаныштымыз!',
    'contact.name': 'Аты',
    'contact.email': 'Email',
    'contact.subject': 'Тақырып',
    'contact.subjectPlaceholder': 'Не туралы жазғыңыз келеді?',
    'contact.message': 'Хабарлама',
    'contact.messagePlaceholder': 'Толығырақ айтыңыз...',
    'contact.send': 'Жіберу',
    'contact.sending': 'Жіберілуде...',
    'contact.messageSent': 'Хабарлама жіберілді!',
    'contact.thankYou': 'Пікіріңіз үшін рахмет. Жақын арада хабарласамыз.',
    'contact.reachUs': 'Сондай-ақ бізге жазуға болады',

    // Common
    'common.loading': 'Жүктелуде...',
    'common.save': 'Сақтау',
    'common.cancel': 'Бас тарту',
    'common.delete': 'Жою',
    'common.edit': 'Өңдеу',
    'common.close': 'Жабу',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'ru' || saved === 'en' || saved === 'kk') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}